- hosts: terraform-ansible
  tasks:
  - name: Instalar Python3, virtualenv
    apt:
      pkg: 
        - python3
        - virtualenv
      update_cache: yes
    become: yes
  - name: Instalar dependencias com pip, django e djangorest
    pip:
      virtualenv: /home/ubuntu/iac/venv
      name:
        - django
        - djangorestframework