- hosts: terraform-ansible
  tasks:
  - name: Instalar Python3, virtualenv
    apt:
      pkg: 
        - python3
        - virtualenv
      update_cache: yes
    become: yes
  - name: Instalar dependencias com pip, django e djangorest
    pip:
      virtualenv: /home/ubuntu/iac/venv
      name:
        - django
        - djangorestframework
  - name: Verificando se o projeto existe
    stat:
      path: /home/ubuntu/iac/setup/settings.py
    register: projeto
  - name: Iniciando projeto
    shell: '. /home/ubuntu/iac/venv/bin/activate; django-admin startproject setup /home/ubuntu/iac/'
    when: not projeto.stat.exists
  - name: Alterando hosts do settings
    lineinfile:
      path: /home/ubuntu/iac/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes